### ISSUE TITLE
obtain basic live data feed to update currently viewed stock

### ISSUE THREAD

**Issue by willyspinner** [cs130-w21/19#13]
## User Story
As a user, I want to obtain a basic live data feed to update currently viewed stock chart in real time.

Also, I want to be able to view historical OHLC data (max 1Y ago). Specifically:
- able to see different resolutions (`30mins, 1hr, D, W, M`, etc.) of stock data
- Able to scroll back / pan the graph to view earlier data points, fetching them if needed using our API. 

## Detailed Description
Provide additional details and context.

## Subtasks (Please also link task PRs here)
- [x] Backend (PR #58 merged)
- [ ] frontend changes

**Comment by willyspinner** [comment]
I propose we use the following arch:

- Backend acts as a proxy to get **historical** OHLC candlestick quote from finnhub (see [here](https://finnhub.io/docs/api/stock-candles)). As a free tier member, we get 1 year back, which isn't the best, but it's free. Note that for now, we don't cache anything yet so that it simplifies our system - also the free tier rate limits for finnhub are quite generous if we don't get a lot of traffic.
- Backend also exposes a Websocket (WS) endpoint 'proxy' that allows client to subscribe to stock updates that come directly from finnhub's own websocket endpoint (only for currently viewed stock). 

Then the frontend will operate as follows:
1. Fetch from our backend the data from 1M, 6M, 1Y ago to now (current time) depending on client's desired resolution. 
2. Subscribe to WS endpoint as mentioned above to add new candlestick points to the chart as live data comes in, AS WELL AS updating the buy & sell widget's price quote.


This will segue to the 'use realtime info to trade stocks' (story #15) pretty nicely as we can piggyback from the (2) request as above to keep track of every stock's most recent prices.

**Comment by willyspinner** [comment]
@ChoiJ0527 @varun1729  if that sounds good to yall we can get started with this ^^

**Comment by ChoiJ0527** [comment]
Sounds good! I'm assuming you're going to go into more details about the back-front connection in the meeting?

**Comment by willyspinner** [comment]
yes

**Comment by willyspinner** [comment]
don't forget to handle fetching for older data when the user scrolls / pans the graph to see older datapoints, as well as using the different resolutions - You can use the `from` , `to` & `resolution` query params as stated in the api docs
