### ISSUE TITLE
[BUG] - Eliminate dual `package.json` structure

### ISSUE THREAD

**Issue by willyspinner** [cs130-w21/19#28]
## Description
we seem to have some confusion with the `package.json` files. Need to change it so that we can use only one package.json for frontend and backend.

NOTE: let's do this after the stories to add authentication & buy sell feature frontends are setup. Makes it easier.

Also, every frontend stakeholder needs to review and approve this. 
## Steps to Reproduce
look at our repo structure :) 

## Expected Behavior
Give a clear and concise description of what should be the expected behavior.

## Additional Context
Enter any other details such as dependencies, environment, examples, etc.

## Relevant screenshots
If applicable, add screenshots to help illustrate the bug.

**Comment by akanksha003** [comment]
Hey! Here's an article I found that offers a solution to this problem, if we're willing to keep the frontend and backend package.json files uncoupled! Hope this helps.

[https://engineering.hexacta.com/decoupling-front-end-and-back-end-530d55b998a5](url)

**Comment by willyspinner** [comment]
@akanksha003  I agree. I think we should make the frontend and backend separate, and thus have separate backend and frontend folders. I've started a PR for this
