### ISSUE TITLE
Cleaner UI in frontend

### ISSUE THREAD

**Issue by willyspinner** [cs130-w21/19#51]
## User Story
As a user I would like a cleaner and more aesthetically pleasing UI.

## Detailed Description
We are using `react-bootstrap` UI components without any modifications. This Story serves to change the look and feel of the website according to our UI mockups, and to define style conventions that we must all use from now on.

## Subtasks (Please also link task PRs here)
- [#76]
- []
- []

**Comment by ChoiJ0527** [comment]
While this story was initially opened for the sake of small UI design changes, we as a team decided to change our entire UI/UX flow to improve the user experience. We did this by streamlining the features of our application into more intuitive groups.

### Mockup

**Market**

![Page_1_Copy_1](https://user-images.githubusercontent.com/16259597/109284127-5ce1b500-77d4-11eb-8d9a-7a47053ec96f.png)

The market page has three main features.

- Watchlist
    - list of stocks the user is watching
    - clicking on stock ticker will select the stock and show the stock's quote
- Quote
    - display information for the selected stock
        - display user position statistics
        - display general stock statistics
- Buy/Sell
    - show how many shares of the selected stock the user currently owns
    - show user's buying power
    - allow the users to buy or sell specified number of shares
        - allow the user to specify number of shares to buy or sell
        - display the value of the specified number of shares (market value x shares)

**Profile**

![Page_1_Copy_Copy_1](https://user-images.githubusercontent.com/16259597/109285736-49374e00-77d6-11eb-90b3-1b3244f6c48d.png)

- Portfolio
    - list of stocks the user owns
    - display graph of the user's portfolio history
    - clicking on stock ticker will select the stock and show the stock's quote in the Market page
- Performance
    - percentage gain of the stocks that the user owns
    - display graph of the user's portfolio history
    - clicking on stock ticker will select the stock and show the stock's quote in the Market page
- History
    - display a table of the user's buy/sell transactions
        - display amount of shares exchanged
        - display portfolio value after transaction

**Comment by willyspinner** [comment]
Why did we close this issue? It's not implemented yet.
