### ISSUE TITLE
[BUG] - Portfolio Table on Profile Page 

### ISSUE THREAD

**Issue by akanksha003** [cs130-w21/19#72]
## Description
The portfolio table in the Profile page throws an error when the user clicks on any given row because the component expects an onSelectStock propType. We use this to update the ticker information on the chart page. However, we don't need this behavior on the profile page. There is no event that must be fired after the user clicks on a portfolio item on the Profile page (based on our current design).
 
## Steps to Reproduce
Steps to reproduce the bug:
- [ ] Go to Profile Page
- [ ] Click on item in portfolio table

## Expected Behavior
Clicking on the item should not initiate another event

## Additional Context
Enter any other details such as dependencies, environment, examples, etc.

## Relevant screenshots
If applicable, add screenshots to help illustrate the bug.

**Comment by willyspinner** [comment]
yes good point! nice catch
